# This docker-compose file is used when BUILD_OR_PULL_IMAGES=pull
# All relevant containers are pulled from the registry

services:
  backend:
    image: kfwopensource/truspace-backend:${VERSION:-latest}

  frontend:
    image: kfwopensource/truspace-frontend:${VERSION:-latest

  ipfs0:
    image: ipfs/kubo:release

  cluster0:
    image: ipfs/ipfs-cluster:latest}

  webui:
    image: ghcr.io/open-webui/open-webui:ollama